Backend: Vivado
Board: null
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 64
    Strategy: Resource
IOType: io_stream
InputData: null
KerasModel: !keras_model 'Deepcalo_LARGE_FULL_MODEL/keras_model.h5'
OutputDir: Deepcalo_LARGE_FULL_MODEL
OutputPredictions: null
ProjectName: myproject
Stamp: Bb6A871b
XilinxPart: xczu9eg-ffvb1156-2-e
