// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2,HLS_SYN_LUT=11,HLS_VERSION=2019_2}" *)

module myproject (
        em_barrel_V_data_V_TDATA,
        layer55_out_V_data_V_TDATA,
        const_size_in_1,
        const_size_out_1,
        s3_V_address0,
        s3_V_ce0,
        s3_V_d0,
        s3_V_q0,
        s3_V_we0,
        b3_V_address0,
        b3_V_ce0,
        b3_V_d0,
        b3_V_q0,
        b3_V_we0,
        w4_V_address0,
        w4_V_ce0,
        w4_V_d0,
        w4_V_q0,
        w4_V_we0,
        b4_V_address0,
        b4_V_ce0,
        b4_V_d0,
        b4_V_q0,
        b4_V_we0,
        w9_V_address0,
        w9_V_ce0,
        w9_V_d0,
        w9_V_q0,
        w9_V_we0,
        b9_V_address0,
        b9_V_ce0,
        b9_V_d0,
        b9_V_q0,
        b9_V_we0,
        w13_V_address0,
        w13_V_ce0,
        w13_V_d0,
        w13_V_q0,
        w13_V_we0,
        b13_V_address0,
        b13_V_ce0,
        b13_V_d0,
        b13_V_q0,
        b13_V_we0,
        w18_V_address0,
        w18_V_ce0,
        w18_V_d0,
        w18_V_q0,
        w18_V_we0,
        b18_V_address0,
        b18_V_ce0,
        b18_V_d0,
        b18_V_q0,
        b18_V_we0,
        w22_V_address0,
        w22_V_ce0,
        w22_V_d0,
        w22_V_q0,
        w22_V_we0,
        b22_V_address0,
        b22_V_ce0,
        b22_V_d0,
        b22_V_q0,
        b22_V_we0,
        w27_V_address0,
        w27_V_ce0,
        w27_V_d0,
        w27_V_q0,
        w27_V_we0,
        b27_V_address0,
        b27_V_ce0,
        b27_V_d0,
        b27_V_q0,
        b27_V_we0,
        w31_V_address0,
        w31_V_ce0,
        w31_V_d0,
        w31_V_q0,
        w31_V_we0,
        b31_V_address0,
        b31_V_ce0,
        b31_V_d0,
        b31_V_q0,
        b31_V_we0,
        w36_V_address0,
        w36_V_ce0,
        w36_V_d0,
        w36_V_q0,
        w36_V_we0,
        b36_V_address0,
        b36_V_ce0,
        b36_V_d0,
        b36_V_q0,
        b36_V_we0,
        w40_V_address0,
        w40_V_ce0,
        w40_V_d0,
        w40_V_q0,
        w40_V_we0,
        b40_V_address0,
        b40_V_ce0,
        b40_V_d0,
        b40_V_q0,
        b40_V_we0,
        w45_V_address0,
        w45_V_ce0,
        w45_V_d0,
        w45_V_q0,
        w45_V_we0,
        b45_V_address0,
        b45_V_ce0,
        b45_V_d0,
        b45_V_q0,
        b45_V_we0,
        w49_V_address0,
        w49_V_ce0,
        w49_V_d0,
        w49_V_q0,
        w49_V_we0,
        b49_V_address0,
        b49_V_ce0,
        b49_V_d0,
        b49_V_q0,
        b49_V_we0,
        w53_V_address0,
        w53_V_ce0,
        w53_V_d0,
        w53_V_q0,
        w53_V_we0,
        b53_V_address0,
        b53_V_ce0,
        b53_V_d0,
        b53_V_q0,
        b53_V_we0,
        ap_clk,
        ap_rst_n,
        const_size_in_1_ap_vld,
        const_size_out_1_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


input  [15:0] em_barrel_V_data_V_TDATA;
input  [15:0] layer55_out_V_data_V_TDATA;
output  [15:0] const_size_in_1;
output  [15:0] const_size_out_1;
output  [1:0] s3_V_address0;
output   s3_V_ce0;
output  [15:0] s3_V_d0;
input  [15:0] s3_V_q0;
output   s3_V_we0;
output  [1:0] b3_V_address0;
output   b3_V_ce0;
output  [15:0] b3_V_d0;
input  [15:0] b3_V_q0;
output   b3_V_we0;
output  [10:0] w4_V_address0;
output   w4_V_ce0;
output  [15:0] w4_V_d0;
input  [15:0] w4_V_q0;
output   w4_V_we0;
output  [3:0] b4_V_address0;
output   b4_V_ce0;
output  [15:0] b4_V_d0;
input  [15:0] b4_V_q0;
output   b4_V_we0;
output  [12:0] w9_V_address0;
output   w9_V_ce0;
output  [15:0] w9_V_d0;
input  [15:0] w9_V_q0;
output   w9_V_we0;
output  [4:0] b9_V_address0;
output   b9_V_ce0;
output  [15:0] b9_V_d0;
input  [15:0] b9_V_q0;
output   b9_V_we0;
output  [13:0] w13_V_address0;
output   w13_V_ce0;
output  [15:0] w13_V_d0;
input  [15:0] w13_V_q0;
output   w13_V_we0;
output  [4:0] b13_V_address0;
output   b13_V_ce0;
output  [15:0] b13_V_d0;
input  [15:0] b13_V_q0;
output   b13_V_we0;
output  [14:0] w18_V_address0;
output   w18_V_ce0;
output  [15:0] w18_V_d0;
input  [15:0] w18_V_q0;
output   w18_V_we0;
output  [5:0] b18_V_address0;
output   b18_V_ce0;
output  [15:0] b18_V_d0;
input  [15:0] b18_V_q0;
output   b18_V_we0;
output  [15:0] w22_V_address0;
output   w22_V_ce0;
output  [15:0] w22_V_d0;
input  [15:0] w22_V_q0;
output   w22_V_we0;
output  [5:0] b22_V_address0;
output   b22_V_ce0;
output  [15:0] b22_V_d0;
input  [15:0] b22_V_q0;
output   b22_V_we0;
output  [16:0] w27_V_address0;
output   w27_V_ce0;
output  [15:0] w27_V_d0;
input  [15:0] w27_V_q0;
output   w27_V_we0;
output  [6:0] b27_V_address0;
output   b27_V_ce0;
output  [15:0] b27_V_d0;
input  [15:0] b27_V_q0;
output   b27_V_we0;
output  [17:0] w31_V_address0;
output   w31_V_ce0;
output  [15:0] w31_V_d0;
input  [15:0] w31_V_q0;
output   w31_V_we0;
output  [6:0] b31_V_address0;
output   b31_V_ce0;
output  [15:0] b31_V_d0;
input  [15:0] b31_V_q0;
output   b31_V_we0;
output  [18:0] w36_V_address0;
output   w36_V_ce0;
output  [15:0] w36_V_d0;
input  [15:0] w36_V_q0;
output   w36_V_we0;
output  [7:0] b36_V_address0;
output   b36_V_ce0;
output  [15:0] b36_V_d0;
input  [15:0] b36_V_q0;
output   b36_V_we0;
output  [19:0] w40_V_address0;
output   w40_V_ce0;
output  [15:0] w40_V_d0;
input  [15:0] w40_V_q0;
output   w40_V_we0;
output  [7:0] b40_V_address0;
output   b40_V_ce0;
output  [15:0] b40_V_d0;
input  [15:0] b40_V_q0;
output   b40_V_we0;
output  [19:0] w45_V_address0;
output   w45_V_ce0;
output  [15:0] w45_V_d0;
input  [15:0] w45_V_q0;
output   w45_V_we0;
output  [7:0] b45_V_address0;
output   b45_V_ce0;
output  [15:0] b45_V_d0;
input  [15:0] b45_V_q0;
output   b45_V_we0;
output  [15:0] w49_V_address0;
output   w49_V_ce0;
output  [15:0] w49_V_d0;
input  [15:0] w49_V_q0;
output   w49_V_we0;
output  [7:0] b49_V_address0;
output   b49_V_ce0;
output  [15:0] b49_V_d0;
input  [15:0] b49_V_q0;
output   b49_V_we0;
output  [7:0] w53_V_address0;
output   w53_V_ce0;
output  [15:0] w53_V_d0;
input  [15:0] w53_V_q0;
output   w53_V_we0;
output  [0:0] b53_V_address0;
output   b53_V_ce0;
output  [15:0] b53_V_d0;
input  [15:0] b53_V_q0;
output   b53_V_we0;
input   ap_clk;
input   ap_rst_n;
output   const_size_in_1_ap_vld;
output   const_size_out_1_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    Block_proc_U0_ap_start;
wire    Block_proc_U0_ap_done;
wire    Block_proc_U0_ap_continue;
wire    Block_proc_U0_ap_idle;
wire    Block_proc_U0_ap_ready;
wire   [15:0] Block_proc_U0_const_size_in_1;
wire    Block_proc_U0_const_size_in_1_ap_vld;
wire   [15:0] Block_proc_U0_const_size_out_1;
wire    Block_proc_U0_const_size_out_1_ap_vld;
wire    ap_sync_continue;
wire    ap_sync_done;
wire    ap_sync_ready;
wire    Block_proc_U0_start_full_n;
wire    Block_proc_U0_start_write;

Block_proc Block_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_proc_U0_ap_start),
    .ap_done(Block_proc_U0_ap_done),
    .ap_continue(Block_proc_U0_ap_continue),
    .ap_idle(Block_proc_U0_ap_idle),
    .ap_ready(Block_proc_U0_ap_ready),
    .const_size_in_1(Block_proc_U0_const_size_in_1),
    .const_size_in_1_ap_vld(Block_proc_U0_const_size_in_1_ap_vld),
    .const_size_out_1(Block_proc_U0_const_size_out_1),
    .const_size_out_1_ap_vld(Block_proc_U0_const_size_out_1_ap_vld)
);

assign Block_proc_U0_ap_continue = 1'b1;

assign Block_proc_U0_ap_start = ap_start;

assign Block_proc_U0_start_full_n = 1'b1;

assign Block_proc_U0_start_write = 1'b0;

assign ap_done = Block_proc_U0_ap_done;

assign ap_idle = Block_proc_U0_ap_idle;

assign ap_ready = Block_proc_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = Block_proc_U0_ap_done;

assign ap_sync_ready = Block_proc_U0_ap_ready;

assign b13_V_address0 = 5'd0;

assign b13_V_ce0 = 1'b0;

assign b13_V_d0 = 16'd0;

assign b13_V_we0 = 1'b0;

assign b18_V_address0 = 6'd0;

assign b18_V_ce0 = 1'b0;

assign b18_V_d0 = 16'd0;

assign b18_V_we0 = 1'b0;

assign b22_V_address0 = 6'd0;

assign b22_V_ce0 = 1'b0;

assign b22_V_d0 = 16'd0;

assign b22_V_we0 = 1'b0;

assign b27_V_address0 = 7'd0;

assign b27_V_ce0 = 1'b0;

assign b27_V_d0 = 16'd0;

assign b27_V_we0 = 1'b0;

assign b31_V_address0 = 7'd0;

assign b31_V_ce0 = 1'b0;

assign b31_V_d0 = 16'd0;

assign b31_V_we0 = 1'b0;

assign b36_V_address0 = 8'd0;

assign b36_V_ce0 = 1'b0;

assign b36_V_d0 = 16'd0;

assign b36_V_we0 = 1'b0;

assign b3_V_address0 = 2'd0;

assign b3_V_ce0 = 1'b0;

assign b3_V_d0 = 16'd0;

assign b3_V_we0 = 1'b0;

assign b40_V_address0 = 8'd0;

assign b40_V_ce0 = 1'b0;

assign b40_V_d0 = 16'd0;

assign b40_V_we0 = 1'b0;

assign b45_V_address0 = 8'd0;

assign b45_V_ce0 = 1'b0;

assign b45_V_d0 = 16'd0;

assign b45_V_we0 = 1'b0;

assign b49_V_address0 = 8'd0;

assign b49_V_ce0 = 1'b0;

assign b49_V_d0 = 16'd0;

assign b49_V_we0 = 1'b0;

assign b4_V_address0 = 4'd0;

assign b4_V_ce0 = 1'b0;

assign b4_V_d0 = 16'd0;

assign b4_V_we0 = 1'b0;

assign b53_V_address0 = 1'd0;

assign b53_V_ce0 = 1'b0;

assign b53_V_d0 = 16'd0;

assign b53_V_we0 = 1'b0;

assign b9_V_address0 = 5'd0;

assign b9_V_ce0 = 1'b0;

assign b9_V_d0 = 16'd0;

assign b9_V_we0 = 1'b0;

assign const_size_in_1 = Block_proc_U0_const_size_in_1;

assign const_size_in_1_ap_vld = Block_proc_U0_const_size_in_1_ap_vld;

assign const_size_out_1 = Block_proc_U0_const_size_out_1;

assign const_size_out_1_ap_vld = Block_proc_U0_const_size_out_1_ap_vld;

assign s3_V_address0 = 2'd0;

assign s3_V_ce0 = 1'b0;

assign s3_V_d0 = 16'd0;

assign s3_V_we0 = 1'b0;

assign w13_V_address0 = 14'd0;

assign w13_V_ce0 = 1'b0;

assign w13_V_d0 = 16'd0;

assign w13_V_we0 = 1'b0;

assign w18_V_address0 = 15'd0;

assign w18_V_ce0 = 1'b0;

assign w18_V_d0 = 16'd0;

assign w18_V_we0 = 1'b0;

assign w22_V_address0 = 16'd0;

assign w22_V_ce0 = 1'b0;

assign w22_V_d0 = 16'd0;

assign w22_V_we0 = 1'b0;

assign w27_V_address0 = 17'd0;

assign w27_V_ce0 = 1'b0;

assign w27_V_d0 = 16'd0;

assign w27_V_we0 = 1'b0;

assign w31_V_address0 = 18'd0;

assign w31_V_ce0 = 1'b0;

assign w31_V_d0 = 16'd0;

assign w31_V_we0 = 1'b0;

assign w36_V_address0 = 19'd0;

assign w36_V_ce0 = 1'b0;

assign w36_V_d0 = 16'd0;

assign w36_V_we0 = 1'b0;

assign w40_V_address0 = 20'd0;

assign w40_V_ce0 = 1'b0;

assign w40_V_d0 = 16'd0;

assign w40_V_we0 = 1'b0;

assign w45_V_address0 = 20'd0;

assign w45_V_ce0 = 1'b0;

assign w45_V_d0 = 16'd0;

assign w45_V_we0 = 1'b0;

assign w49_V_address0 = 16'd0;

assign w49_V_ce0 = 1'b0;

assign w49_V_d0 = 16'd0;

assign w49_V_we0 = 1'b0;

assign w4_V_address0 = 11'd0;

assign w4_V_ce0 = 1'b0;

assign w4_V_d0 = 16'd0;

assign w4_V_we0 = 1'b0;

assign w53_V_address0 = 8'd0;

assign w53_V_ce0 = 1'b0;

assign w53_V_d0 = 16'd0;

assign w53_V_we0 = 1'b0;

assign w9_V_address0 = 13'd0;

assign w9_V_ce0 = 1'b0;

assign w9_V_d0 = 16'd0;

assign w9_V_we0 = 1'b0;

endmodule //myproject
